log_dir: experiments_ns2d/ns2d_re200_stage2
overwrite_exist: True
device: cuda:0
project_name: latent-pde-ns2d-stage2

# option for vq encoder
latent_dim: 16     # Latent dimension n_z (default: 4)
Ly: 64
Lx: 64
resolution: 64
in_channels: 1    # voriticity
latent_resolution: 8
is_periodic: True

encoder_channels: [64, 64, 64, 128, 128]
fourier_resolutions: []  # truncate high-frequency components
encoder_res_blocks: 1
use_attn_enc: False

use_fa: True
decoder_channels: [128, 128, 64, 64]
attn_resolutions: [16, 32]
decoder_res_blocks: 1
final_smoothing: False
attn_heads: 8
attn_dim: 64
disable_coarse_attn: False
noise_level: 0.

pretrained_checkpoint_path: /home/cmu-mail-3090/Zijie_2/latent-pde-solver/experiments_ns2d/ns2d_re200_stage1/checkpoints/vqgan_epoch_final.pt

# option for latent resnet
prop_n_block: 3
prop_n_embd: 128
dilation: 2

data_dir: /home/cmu-mail-3090/Zijie/pde_data/ns2d_1e-4_solution_N5000.npz
case_len: 30
dataset_stat: ns2d_re200_stat_new.npz
num_case: 1000
interval: 1
out_tw: 2

batch_size: 32
epochs: 500
learning_rate: 5.e-4
ckpt_every: 50
