log_dir: experiments_SW_stage1/shallow-water-stage1-new
overwrite_exist: True
device: cuda:0
project_name: lnpde-sw-stage1
resume_training: True

latent_dim: 64     # Latent dimension n_z (default: 4)
Ly: 96
Lx: 192
resolutions: [96, 192]
in_channels: 3    # voriticity
latent_resolution: 12
periodic_direction: x
hw_ratio: 2

encoder_channels: [64, 64, 64, 128, 128]  # compression ratio: 16
fourier_resolutions: []  # truncate high-frequency components
encoder_res_blocks: 1

use_fa: True
decoder_channels: [128, 128, 64, 64]
attn_resolutions: [24, 48]
decoder_res_blocks: 1
final_smoothing: False
decoder_attn_heads: 8
decoder_attn_dim: 64
disable_coarse_attn: False

train_data_dir: /data/zijie_data/pde_data/ShallowWater-2D/train.zarr
test_data_dir: /data/zijie_data/pde_data/ShallowWater-2D/test.zarr
dataset_stat: /data/zijie_data/pde_data/ShallowWater-2D/normstats.pt

case_len: 88
num_case: 1400
batch_size: 64
epochs: 200
learning_rate: 3.e-5
beta1: 0.5
beta2: 0.9
ckpt_every: 40