log_dir: experiments_SW_stage2_new/shallow-water-tw5
overwrite_exist: True
device: cuda:0
project_name: lnpde-sw-stage2

latent_dim: 64     # Latent dimension n_z (default: 4)
Ly: 96
Lx: 192
resolutions: [96, 192]
in_channels: 3    # voriticity
latent_resolution: 12
periodic_direction: x
hw_ratio: 2

encoder_channels: [64, 64, 64, 128, 128]  # compression ratio: 16
fourier_resolutions: []  # truncate high-frequency components
encoder_res_blocks: 1

use_fa: True
decoder_channels: [128, 128, 64, 64]
attn_resolutions: [24, 48]
decoder_res_blocks: 1
final_smoothing: False
decoder_attn_heads: 8
decoder_attn_dim: 64
disable_coarse_attn: False

# option for latent resnet
prop_n_block: 4
prop_n_embd: 128
dilation: 3

pretrained_checkpoint_path: experiments_SW_stage1/shallow-water-stage1-new/checkpoints/vqgan_epoch_160.pt

train_data_dir: /data/zijie_data/pde_data/ShallowWater-2D/train.zarr
test_data_dir: /data/zijie_data/pde_data/ShallowWater-2D/test.zarr
dataset_stat: /data/zijie_data/pde_data/ShallowWater-2D/normstats.pt
case_len: 88
out_tw: 5
interval: 2
num_case: 1400

batch_size: 32
epochs: 100
learning_rate: 3.e-4
ckpt_every: 20