log_dir: twophase_experiments_stage1/twopahse_stage1_old_dataset
overwrite_exist: True
device: cuda:0
project_name: vq-twopahse-stage1

latent_dim: 64     # Latent dimension n_z (default: 4)
Ly: 61
Lx: 121
resolutions: [61, 121]
in_channels: 4    # voriticity
latent_resolution: 7
is_periodic: False
hw_ratio: 2

encoder_channels: [64, 64, 64, 128, 128]  # compression ratio: 16
fourier_resolutions: []  # truncate high-frequency components
encoder_res_blocks: 1
cond_channels: 1
cond_emb_channels: 64

use_fa: True
decoder_channels: [128, 128, 64, 64]
attn_resolutions: [15, 30]
decoder_res_blocks: 1
final_smoothing: False
decoder_attn_heads: 8
decoder_attn_dim: 64

data_dir: /home/cmu-mail-3090/Zijie_2/pde_data/processed_BulkData_latest
case_len: 79
dataset_stat: twophase_stat_old.npz
num_case: 666

batch_size: 32
epochs: 500
learning_rate: 3.e-5
beta1: 0.5
beta2: 0.9
physics_factor: -1 #  0.5
ckpt_every: 50